title:            Dashamir Hoxha
description:      When I do something that is not trivial and needs some 
    research, I try to summarize it and write it down, in case that
    I will need later to do the same thing again. It may also be useful
    for other people that could be trying to do something similar.
disqus_shortname: dashohoxha
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              //dashohoxha.fs.al

# Owner/author information
owner:
  name:           Dashamir Hoxha
  avatar:         dashamir.jpg
  # bio:            "Computer Engineer with experience in software engineering, web application development, linux and network configuration/administraton, etc."
  bio:
  email:          dashohoxha@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        dashohoxha
  facebook:       
  github:         dashohoxha
  academia:       http://independent.academia.edu/DashamirHoxha
  stackexchange:  http://stackexchange.com/users/990339/dashohoxha
  linkedin:       dashohoxha
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +DashamirHoxha

# Background image to be tiled on all pages
background:       textured-paper.jpg

# Analytics and webmaster tools stuff goes here
google_analytics: UA-57417723-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Tirane
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
